title: Ben Gill
email: benggill@protonmail.com
description: Creative Copywriter & Field Producer
baseurl: "/bengillabides"
url: ""
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

sass:
  implementation: sassc
  style: compact
  sass_dir: _sass
  line_comments: false
  sourcemap: always

# jekyll-paginate configuration
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
